### ISSUE TITLE
Did not work for VS Code 1.77.3

### ISSUE THREAD

**Issue by sanjaygodiya** [OH318/J-Diagram#5]
I tried to generate class diagram for a springboot mvc project but it didn't work, it asked to select the folder where java files are there, I tried selecting the root folder of the project (as all java files are in subfolders) it didn't work, selected service folder which has multiple java files but it didn't work. I am using Java 1.8.0_341 on Win 11. 

Just read the readme, its not supported for Windows :(

**Comment by jiniljeil** [comment]
The problem that did not run on Windows has been fixed.
